; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano_every]
platform = atmelmegaavr
board = nano_every
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/adafruit/Adafruit_INA219
	adafruit/Adafruit AHTX0@^2.0.5
	
; force inclusion of floating support in printf, sprintf, snprintf, etc
build_flags = -Wl,-u,vfprintf -lprintf_flt -lm
